name: physphile-vue-template
private: true
version: 0.0.0
type: module
scripts:
    dev: vite
    build: vue-tsc && vite build
    preview: vite preview
    lint: eslint --ext ts,vue . --fix
    format: prettier . --write
    stylelint: stylelint "**/*.{vue,css}" --fix
    check: vue-tsc && pnpm run format && pnpm run lint && pnpm run stylelint
dependencies:
    pinia: '^2.1.7'
    vue: '^3.3.11'
    vue-router: '^4.2.5'
    vuetify: '^3.4.6'
devDependencies:
    '@vitejs/plugin-vue': '^4.5.2'
    '@vue/eslint-config-typescript': '^12.0.0'
    eslint: '^8.55.0'
    eslint-config-prettier: '^9.1.0'
    eslint-plugin-prettier: '^5.0.1'
    eslint-plugin-vue: '^9.19.2'
    postcss-preset-env: '^9.3.0'
    prettier: '^3.1.0'
    stylelint: '^15.11.0'
    stylelint-config-recommended: '^13.0.0'
    stylelint-config-recommended-vue: '^1.5.0'
    stylelint-config-standard: '^34.0.0'
    stylelint-use-nesting: '^4.1.0'
    typescript: '^5.3.3'
    vite: '^4.5.1'
    vite-plugin-stylelint: '^5.2.1'
    vite-plugin-vuetify: '^1.0.2'
    vite-svg-loader: '^5.1.0'
    vue-tsc: '^1.8.25'
